### ISSUE TITLE
Did you configure r1zebra.conf?

### ISSUE THREAD

**Issue by MichaelRren** [qyang18/Mininet-Quagga#2]
Thanks for your sharing, and I have followed your steps and tried to run your QuaggaOSPF.py. However, issue occurs. In r1ospfd.log, there is a log about OSPF:zclient_socket_un failure: 111. Thus, I suspect the issue occurs due to I do not configure r1zebra.conf correctly. Could you please give me some hint about your configuration? Look forward to your reply. Really appreciate.

**Comment by RershallzzZ** [comment]
> Thanks for your sharing, and I have followed your steps and tried to run your QuaggaOSPF.py. However, issue occurs. In r1ospfd.log, there is a log about OSPF:zclient_socket_un failure: 111. Thus, I suspect the issue occurs due to I do not configure r1zebra.conf correctly. Could you please give me some hint about your configuration? Look forward to your reply. Really appreciate.

Have you solved the problem？

**Comment by Hasan-aga** [comment]
> > Thanks for your sharing, and I have followed your steps and tried to run your QuaggaOSPF.py. However, issue occurs. In r1ospfd.log, there is a log about OSPF:zclient_socket_un failure: 111. Thus, I suspect the issue occurs due to I do not configure r1zebra.conf correctly. Could you please give me some hint about your configuration? Look forward to your reply. Really appreciate.
> 
> Have you solved the problem？

did you ever make things work?
